### PR TITLE
chore: update michal's and nick's info

### PR DESCRIPTION
**Pull request by mszpakowski**

### CODE REVIEW

**Review by BeenzSyed — APPROVED** [review]

**Comment by mattgreg** [comment]
@mszpakowski can you rebase and merge this PR to `develop`

**Comment by mszpakowski** [comment]
@mattgreg rebased, but I can't merge it, because I don't have the access to Vercel and can't authorize a deploy

**Comment by mattgreg** [comment]
all you need to do is `git push origin develop` Vercel does the rest. 

or do you not have GH perms to `git push origin develop`? if not @mrinalwadhwa can give you that perm.

**Comment by mszpakowski** [comment]
> all you need to do is `git push origin develop` Vercel does the rest.
Got it, what I meant is that merging this PR via github is blocked by the Vercel check. I didn't think of pushing directly to develop, because in my mind the process was `Open a PR` -> `Get approval` -> `Merge`

> or do you not have GH perms to `git push origin develop`? if not @mrinalwadhwa can give you that perm.
Now that I tried pushing directly to develop it appears that I don't in fact have a permission to do that.

**Comment by mrinalwadhwa** [comment]
Merged in https://github.com/build-trust/ockam-website/pull/688

**Pull request closed without merging**
